sudo: false
language: node_js
matrix:
  fast_finish: true
  include:
    - node_js: "4"
      env: TASK=test-browser
    - node_js: "4"
      env: TASK=test-node
    - node_js: "3"
      env: TASK=test-node
    - node_js: "2"
      env: TASK=test-node
    - node_js: "1"
      env: TASK=test-node
    - node_js: "0.12"
      env: TASK=test-node
    - node_js: "0.10"
      env: TASK=test-node
env:
  global:
    - secure: FvDHR95HJSOUyfskQaR/QL2o7AH1drFOoMovkd9tS9KLLXpL6FZOXSOn2uD4yXp1uLcV788OR6/ZZOArRqUt+DbHGOEa/y/kc19VPr9eEw68HMSoqMEHCO9S5+xFmDGJ3uxifaaVmjBxVcEE/c4I9OIDV5dSZchuNld9CKkN71Y=
    - secure: CdaWP+EV4tCc1VnVtTAm4ACNuOylRErMlhO7lRyr0aMoMeM1mLDneHPJBx+eZ4TY+/7f8CIPW12QHdye0PtR5r2pVkejVLeFQJfdxckPdwxeS0rcJQprqOm1W7D93SNBri5YkdBfGyV+OjTEUy6Mwpipl2RdspE+YuQ8Sl61biM=
script:
  - "npm run ${TASK}"
after_script:
  - 'if [ "${TASK}" == "test-node" ]; then npm i coveralls@2 && cat coverage/lcov.info | coveralls; fi'
notifications:
  irc:
    channels:
      - "irc.freenode.org#primus"
    on_success: change
    on_failure: change
